//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCwebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        
        public int UserID { get; set; }

        [DisplayName("U¿ytkownik")]
        [Required(ErrorMessage ="Te pole jest wymagane")]
        public string UserName { get; set; }
        [DisplayName("Has³o")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Te pole jest wymagane")]
        public string Password { get; set; }

        [DisplayName("Powtórz has³o")]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "Te pole jest wymagane")]
        public string Email { get; set; }
    }
}
